services:
  # phase3 Service
  phase3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres_phase3
    networks:
      - microservices-network

  # PostgreSQL for phase3 Service
  postgres_phase3:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Expose phase3 DB to external port 5433
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-user-data:
    driver: local
  postgres-archive-data:
    driver: local
